services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile

  nginx-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: nginx-service
    depends_on:
      - php


  node-front:
    build:
      context: .
      dockerfile: ./Dockerfile