services:
  php:
    image: ${DOCKER_REGISTRY:-trouptrip}/backend:latest

  nginx:
    image: nginx:alpine
    depends_on:
      - php

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql

  node-front:
    image: ${DOCKER_REGISTRY:-trouptrip}/frontend:latest

volumes:
  db_data: