services:
  php:
    build:
      target: php-prod
    restart: always
    env_file:
      - .env
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      SKIP_DOTENV: 1

  nginx-service:
    restart: always
    networks:
      - default
      - web

  db:
    restart: always

  node-front:
    restart: always
    networks:
      - default
      - web
    environment:
      - NUXT_PUBLIC_API_BASE_URL=https://mon-vrai-domaine.com/api

networks:
  web:
    external: true