server {
    listen 80;
    server_name _;

    root /var/www/html/public;
    index index.php;

    # API routing Symfony
    location / {
        try_files $uri /index.php$is_args$args;
    }

    # PHP-FPM
    location ~ ^/index\.php(/|$) {
        fastcgi_pass php:9000;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        internal;
    }

    # Bloque accès direct aux autres fichiers PHP
    location ~ \.php$ {
        return 404;
    }
}