<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260916190132 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE invitation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, invited_by_id INT NOT NULL, trip_id INT NOT NULL, invited_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F11D61A2A7B4A7E3 ON invitation (invited_by_id)');
        $this->addSql('CREATE INDEX IDX_F11D61A2A5BC2E0E ON invitation (trip_id)');
        $this->addSql('CREATE INDEX IDX_F11D61A2C58DAD6E ON invitation (invited_user_id)');
        $this->addSql('CREATE TABLE trip_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(50) NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(50) NOT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, trip_id INT NOT NULL, member_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9FEBA1D2A5BC2E0E ON trip_member (trip_id)');
        $this->addSql('CREATE INDEX IDX_9FEBA1D27597D3FE ON trip_member (member_id)');
        $this->addSql('ALTER TABLE invitation ADD CONSTRAINT FK_F11D61A2A7B4A7E3 FOREIGN KEY (invited_by_id) REFERENCES trip_member (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invitation ADD CONSTRAINT FK_F11D61A2A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invitation ADD CONSTRAINT FK_F11D61A2C58DAD6E FOREIGN KEY (invited_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip_member ADD CONSTRAINT FK_9FEBA1D2A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip_member ADD CONSTRAINT FK_9FEBA1D27597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity DROP CONSTRAINT fk_ac74095aa5bc2e0e');
        $this->addSql('ALTER TABLE debtor DROP CONSTRAINT fk_edcc8caeb043ec6b');
        $this->addSql('ALTER TABLE debtor DROP CONSTRAINT fk_edcc8caef395db7b');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT fk_2d3a8da6d754cd1b');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT fk_2d3a8da6a5bc2e0e');
        $this->addSql('ALTER TABLE participation DROP CONSTRAINT fk_ab55e24fa5bc2e0e');
        $this->addSql('ALTER TABLE participation DROP CONSTRAINT fk_ab55e24f9d1c3019');
        $this->addSql('ALTER TABLE participation DROP CONSTRAINT fk_ab55e24fa7b4a7e3');
        $this->addSql('ALTER TABLE refund DROP CONSTRAINT fk_5b2c1458a5bc2e0e');
        $this->addSql('ALTER TABLE refund DROP CONSTRAINT fk_5b2c1458b043ec6b');
        $this->addSql('ALTER TABLE refund DROP CONSTRAINT fk_5b2c1458cd53edb6');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT fk_527edb25f4bd7827');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT fk_527edb25a5bc2e0e');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE debtor');
        $this->addSql('DROP TABLE expense');
        $this->addSql('DROP TABLE participation');
        $this->addSql('DROP TABLE refund');
        $this->addSql('DROP TABLE task');
        $this->addSql('ALTER TABLE assignment ADD trip_member_id INT NOT NULL');
        $this->addSql('ALTER TABLE assignment ADD CONSTRAINT FK_30C544BA688892A9 FOREIGN KEY (trip_member_id) REFERENCES trip_member (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_30C544BA688892A9 ON assignment (trip_member_id)');
        $this->addSql('ALTER TABLE personal_item DROP CONSTRAINT fk_2e1122237e3c61f9');
        $this->addSql('ALTER TABLE personal_item ADD CONSTRAINT FK_2E1122237E3C61F9 FOREIGN KEY (owner_id) REFERENCES trip_member (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, trip_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_ac74095aa5bc2e0e ON activity (trip_id)');
        $this->addSql('CREATE TABLE debtor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, debtor_id INT NOT NULL, expense_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_edcc8caeb043ec6b ON debtor (debtor_id)');
        $this->addSql('CREATE INDEX idx_edcc8caef395db7b ON debtor (expense_id)');
        $this->addSql('CREATE TABLE expense (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, amount INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, trip_id INT NOT NULL, spender_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_2d3a8da6a5bc2e0e ON expense (trip_id)');
        $this->addSql('CREATE INDEX idx_2d3a8da6d754cd1b ON expense (spender_id)');
        $this->addSql('CREATE TABLE participation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, trip_id INT NOT NULL, participant_id INT NOT NULL, invited_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_ab55e24fa5bc2e0e ON participation (trip_id)');
        $this->addSql('CREATE INDEX idx_ab55e24fa7b4a7e3 ON participation (invited_by_id)');
        $this->addSql('CREATE INDEX idx_ab55e24f9d1c3019 ON participation (participant_id)');
        $this->addSql('CREATE TABLE refund (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, trip_id INT NOT NULL, debtor_id INT NOT NULL, receiver_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_5b2c1458cd53edb6 ON refund (receiver_id)');
        $this->addSql('CREATE INDEX idx_5b2c1458b043ec6b ON refund (debtor_id)');
        $this->addSql('CREATE INDEX idx_5b2c1458a5bc2e0e ON refund (trip_id)');
        $this->addSql('CREATE TABLE task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deadline TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, trip_id INT NOT NULL, assigned_to_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_527edb25f4bd7827 ON task (assigned_to_id)');
        $this->addSql('CREATE INDEX idx_527edb25a5bc2e0e ON task (trip_id)');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT fk_ac74095aa5bc2e0e FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE debtor ADD CONSTRAINT fk_edcc8caeb043ec6b FOREIGN KEY (debtor_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE debtor ADD CONSTRAINT fk_edcc8caef395db7b FOREIGN KEY (expense_id) REFERENCES expense (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT fk_2d3a8da6d754cd1b FOREIGN KEY (spender_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT fk_2d3a8da6a5bc2e0e FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT fk_ab55e24fa5bc2e0e FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT fk_ab55e24f9d1c3019 FOREIGN KEY (participant_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT fk_ab55e24fa7b4a7e3 FOREIGN KEY (invited_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refund ADD CONSTRAINT fk_5b2c1458a5bc2e0e FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refund ADD CONSTRAINT fk_5b2c1458b043ec6b FOREIGN KEY (debtor_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refund ADD CONSTRAINT fk_5b2c1458cd53edb6 FOREIGN KEY (receiver_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT fk_527edb25f4bd7827 FOREIGN KEY (assigned_to_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT fk_527edb25a5bc2e0e FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invitation DROP CONSTRAINT FK_F11D61A2A7B4A7E3');
        $this->addSql('ALTER TABLE invitation DROP CONSTRAINT FK_F11D61A2A5BC2E0E');
        $this->addSql('ALTER TABLE invitation DROP CONSTRAINT FK_F11D61A2C58DAD6E');
        $this->addSql('ALTER TABLE trip_member DROP CONSTRAINT FK_9FEBA1D2A5BC2E0E');
        $this->addSql('ALTER TABLE trip_member DROP CONSTRAINT FK_9FEBA1D27597D3FE');
        $this->addSql('DROP TABLE invitation');
        $this->addSql('DROP TABLE trip_member');
        $this->addSql('ALTER TABLE assignment DROP CONSTRAINT FK_30C544BA688892A9');
        $this->addSql('DROP INDEX IDX_30C544BA688892A9');
        $this->addSql('ALTER TABLE assignment DROP trip_member_id');
        $this->addSql('ALTER TABLE personal_item DROP CONSTRAINT FK_2E1122237E3C61F9');
        $this->addSql('ALTER TABLE personal_item ADD CONSTRAINT fk_2e1122237e3c61f9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
