<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260518180131 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, trip_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC74095AA5BC2E0E ON activity (trip_id)');
        $this->addSql('CREATE TABLE assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, assigned_quantity INT NOT NULL, is_packed BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, group_item_id INT NOT NULL, assigned_to_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_30C544BA946F0652 ON assignment (group_item_id)');
        $this->addSql('CREATE INDEX IDX_30C544BAF4BD7827 ON assignment (assigned_to_id)');
        $this->addSql('CREATE TABLE debtor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, debtor_id INT NOT NULL, expense_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EDCC8CAEB043EC6B ON debtor (debtor_id)');
        $this->addSql('CREATE INDEX IDX_EDCC8CAEF395DB7B ON debtor (expense_id)');
        $this->addSql('CREATE TABLE expense (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, amount INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, trip_id INT NOT NULL, spender_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2D3A8DA6A5BC2E0E ON expense (trip_id)');
        $this->addSql('CREATE INDEX IDX_2D3A8DA6D754CD1B ON expense (spender_id)');
        $this->addSql('CREATE TABLE group_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, total_quantity INT NOT NULL, unit VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, trip_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_36417E6EA5BC2E0E ON group_item (trip_id)');
        $this->addSql('CREATE TABLE personal_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, quantity INT NOT NULL, is_packed BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, unit VARCHAR(255) NOT NULL, owner_id INT NOT NULL, trip_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2E1122237E3C61F9 ON personal_item (owner_id)');
        $this->addSql('CREATE INDEX IDX_2E112223A5BC2E0E ON personal_item (trip_id)');
        $this->addSql('CREATE TABLE refund (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, trip_id INT NOT NULL, debtor_id INT NOT NULL, receiver_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5B2C1458A5BC2E0E ON refund (trip_id)');
        $this->addSql('CREATE INDEX IDX_5B2C1458B043EC6B ON refund (debtor_id)');
        $this->addSql('CREATE INDEX IDX_5B2C1458CD53EDB6 ON refund (receiver_id)');
        $this->addSql('CREATE TABLE task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deadline TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, trip_id INT NOT NULL, assigned_to_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_527EDB25A5BC2E0E ON task (trip_id)');
        $this->addSql('CREATE INDEX IDX_527EDB25F4BD7827 ON task (assigned_to_id)');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095AA5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assignment ADD CONSTRAINT FK_30C544BA946F0652 FOREIGN KEY (group_item_id) REFERENCES group_item (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assignment ADD CONSTRAINT FK_30C544BAF4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE debtor ADD CONSTRAINT FK_EDCC8CAEB043EC6B FOREIGN KEY (debtor_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE debtor ADD CONSTRAINT FK_EDCC8CAEF395DB7B FOREIGN KEY (expense_id) REFERENCES expense (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA6A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA6D754CD1B FOREIGN KEY (spender_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE group_item ADD CONSTRAINT FK_36417E6EA5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE personal_item ADD CONSTRAINT FK_2E1122237E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE personal_item ADD CONSTRAINT FK_2E112223A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE refund ADD CONSTRAINT FK_5B2C1458A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE refund ADD CONSTRAINT FK_5B2C1458B043EC6B FOREIGN KEY (debtor_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE refund ADD CONSTRAINT FK_5B2C1458CD53EDB6 FOREIGN KEY (receiver_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25F4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE trip ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity DROP CONSTRAINT FK_AC74095AA5BC2E0E');
        $this->addSql('ALTER TABLE assignment DROP CONSTRAINT FK_30C544BA946F0652');
        $this->addSql('ALTER TABLE assignment DROP CONSTRAINT FK_30C544BAF4BD7827');
        $this->addSql('ALTER TABLE debtor DROP CONSTRAINT FK_EDCC8CAEB043EC6B');
        $this->addSql('ALTER TABLE debtor DROP CONSTRAINT FK_EDCC8CAEF395DB7B');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA6A5BC2E0E');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA6D754CD1B');
        $this->addSql('ALTER TABLE group_item DROP CONSTRAINT FK_36417E6EA5BC2E0E');
        $this->addSql('ALTER TABLE personal_item DROP CONSTRAINT FK_2E1122237E3C61F9');
        $this->addSql('ALTER TABLE personal_item DROP CONSTRAINT FK_2E112223A5BC2E0E');
        $this->addSql('ALTER TABLE refund DROP CONSTRAINT FK_5B2C1458A5BC2E0E');
        $this->addSql('ALTER TABLE refund DROP CONSTRAINT FK_5B2C1458B043EC6B');
        $this->addSql('ALTER TABLE refund DROP CONSTRAINT FK_5B2C1458CD53EDB6');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25A5BC2E0E');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25F4BD7827');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE assignment');
        $this->addSql('DROP TABLE debtor');
        $this->addSql('DROP TABLE expense');
        $this->addSql('DROP TABLE group_item');
        $this->addSql('DROP TABLE personal_item');
        $this->addSql('DROP TABLE refund');
        $this->addSql('DROP TABLE task');
        $this->addSql('ALTER TABLE trip DROP updated_at');
        $this->addSql('ALTER TABLE "user" DROP updated_at');
    }
}
