name: preprod workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # On demande au VPS de mettre à jour son image (Déploiement)
      - name: Deploy main branche to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Aller dans le dossier du projet
            cd /opt/apps/trouptrip/prod
            
            # 2. Récupérer les derniers changements
            git fetch origin main
            git reset --hard origin/main
            git clean -fd
            
            # 3. Re-construire l'image localement et relancer le conteneur
            docker compose -f docker-compose.yaml -f docker-compose.prod.yaml -p trouptrip-prod up -d --build
            
            # 4. Nettoyage des images inutilisées
            docker image prune -f